### ISSUE TITLE
DaLao上新啦，火速签到围观

### ISSUE THREAD

**Issue by SoraKasvgano** [mashirozx/wp-gorgeous#1]
DaLao上新啦，火速签到围观

**Comment by mashirozx** [comment]
一年前的主题，做了半截不想做了。。今天清服务器才想起。。

**Comment by mashirozx** [comment]
真正的新主题在这里😏 https://github.com/mashirozx/sakura2

**Comment by SoraKasvgano** [comment]
> 真正的新主题在这里😏 https://github.com/mashirozx/sakura2

卧槽2已经出来了，是直接覆盖还是 另外新建一个文件夹丢进去

**Comment by mashirozx** [comment]
2还没做好，不要放生产环境
